### PR TITLE
[ART-2146] add new packages

### PR DESCRIPTION
**Pull request by Ximinhan**
we want to use this image as base image for tekton pipeline, add some necessary packages

### CODE REVIEW

**Review by thiagoalessio — APPROVED** [review]
/lgtm

**Review by thiagoalessio — CHANGES_REQUESTED** [review]
https://quay.io/repository/openshift-art/art-ci-toolkit/build/c5d9fa90-1caf-487f-90bd-479b8ad0489c

**Comment by Ximinhan** [comment]
I am not authorized to view builds logs. @thiagoalessio

**Comment by Ximinhan** [comment]
https://quay.io/repository/openshift-art/art-ci-toolkit/build/3c0b3799-b16d-4877-8a5e-e754e0e52f0c

**Pull request merged**
